import { StyleSheet } from "react-native";

import { fontFamily } from "../../constants/fonts";
import { colors, radii, spacing, typography } from "../../constants/theme";

export const onboardingStyles = StyleSheet.create({
  introSafe: {
    flex: 1,
    backgroundColor: colors.background,
    padding: spacing.lg,
    justifyContent: "flex-start",
  },
  introTopRow: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
  },
  introTopRight: {
    flexDirection: "row",
    alignItems: "center",
    gap: spacing.md,
  },
  introSignIn: {
    color: colors.primary,
    fontFamily: fontFamily.bodyBold,
    ...typography.caption,
  },
  introSkip: {
    color: colors.textSecondary,
    fontFamily: fontFamily.bodyBold,
    ...typography.caption,
  },
  introDots: { color: colors.textSecondary, ...typography.caption },
  introSlide: { flex: 1, justifyContent: "flex-start", gap: spacing.sm, paddingTop: spacing.sm },
  introVisualWrap: {
    alignSelf: "center",
    width: "96%",
    maxWidth: 380,
    height: 360,
    borderRadius: 24,
    overflow: "hidden",
    borderWidth: 1,
    borderColor: colors.border,
    backgroundColor: colors.surface,
  },
  introVisualImage: { width: "100%", height: "100%" },
  introHiddenPreload: { width: 0, height: 0, opacity: 0, position: "absolute" },
  introCopyWrap: { gap: spacing.sm, paddingTop: spacing.md, paddingHorizontal: spacing.xs },
  introHeroTitle: {
    color: colors.textPrimary,
    fontFamily: fontFamily.heading,
    fontSize: 26,
    lineHeight: 32,
  },
  introHeroBody: { color: colors.textSecondary, ...typography.body, lineHeight: 22 },
  introBottom: { gap: spacing.md, paddingTop: spacing.sm },
  introPaginationRow: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    gap: spacing.xs,
  },
  introPageDot: {
    width: 8,
    height: 8,
    borderRadius: 999,
    backgroundColor: "rgba(255,255,255,0.22)",
  },
  introPageDotActive: {
    width: 24,
    backgroundColor: colors.primary,
  },
  goalScroll: { gap: spacing.md, paddingBottom: spacing.sm },
  goalGrid: { flexDirection: "row", flexWrap: "wrap", gap: spacing.sm },
  goalCard: {
    width: "48%",
    minHeight: 96,
    paddingHorizontal: spacing.md,
    paddingVertical: spacing.md,
    borderRadius: radii.lg,
    borderWidth: 1,
    borderColor: colors.border,
    backgroundColor: colors.surface,
    gap: 2,
  },
  goalCardOn: {
    borderColor: colors.primary,
    backgroundColor: "rgba(255,61,0,0.1)",
  },
  goalCardValue: {
    color: colors.textPrimary,
    fontFamily: fontFamily.heading,
    fontSize: 28,
    lineHeight: 32,
  },
  goalCardValueOn: { color: colors.primary },
  goalCardLabel: {
    color: colors.textSecondary,
    fontFamily: fontFamily.bodyMedium,
    ...typography.caption,
  },
  goalCardLabelOn: { color: colors.textPrimary },
  goalInfoCard: {
    borderWidth: 1,
    borderColor: colors.border,
    borderRadius: radii.lg,
    backgroundColor: "rgba(255,255,255,0.03)",
    padding: spacing.md,
    gap: 4,
  },
  goalInfoTitle: {
    color: colors.textPrimary,
    fontFamily: fontFamily.bodyBold,
    ...typography.body,
  },
  goalInfoBody: {
    color: colors.textSecondary,
    ...typography.caption,
  },
  notifSafe: {
    flex: 1,
    backgroundColor: colors.background,
    padding: spacing.lg,
    justifyContent: "flex-end",
    gap: spacing.sm,
  },
  notifBody: { flex: 1, justifyContent: "center", gap: spacing.sm },
  notifTitle: {
    color: colors.textPrimary,
    fontFamily: fontFamily.heading,
    fontSize: 28,
    lineHeight: 34,
  },
  loopAccent: { color: colors.primary, fontFamily: fontFamily.heading },
  notifSubtitle: {
    color: colors.textSecondary,
    fontFamily: fontFamily.body,
    ...typography.body,
    lineHeight: 22,
  },
  notifCard: {
    marginTop: spacing.md,
    borderWidth: 1,
    borderColor: colors.border,
    borderRadius: radii.lg,
    backgroundColor: colors.surface,
    padding: spacing.md,
    gap: spacing.xs,
  },
  notifCardTitle: {
    color: colors.textPrimary,
    fontFamily: fontFamily.bodyBold,
    ...typography.body,
    marginBottom: spacing.xs,
  },
  notifBenefit: {
    color: colors.textSecondary,
    ...typography.caption,
  },
  secondaryBtn: { alignItems: "center", paddingVertical: spacing.md },
  secondaryTxt: {
    color: colors.textSecondary,
    fontFamily: fontFamily.bodyBold,
    ...typography.body,
  },
});
