import {
  Activity,
  AudioWaveform,
  Blend,
  Boxes,
  Cable,
  ChartColumn,
  CircleDot,
  Contrast,
  Copy,
  Disc3,
  Drum,
  Flame,
  Gauge,
  Guitar,
  Headphones,
  House,
  Keyboard,
  Layers,
  LayoutList,
  LayoutPanelTop,
  Library,
  Magnet,
  Merge,
  Mic,
  MicVocal,
  MoveHorizontal,
  Music,
  Orbit,
  Package,
  PenLine,
  Piano,
  Repeat,
  Rocket,
  Scissors,
  Shuffle,
  SlidersHorizontal,
  SlidersVertical,
  Sparkles,
  Spline,
  Target,
  Volume2,
  WandSparkles,
  Waves,
  Workflow,
  Zap,
  type LucideIcon,
} from "lucide-react-native";

import type { SkillBranch, SkillFocusId } from "./skills";

export const SKILL_BRANCH_ICONS: Record<SkillBranch, LucideIcon> = {
  beat_making: Drum,
  mixing: SlidersVertical,
  mastering: Disc3,
  sound_design: AudioWaveform,
  recording: Mic,
  songwriting: PenLine,
  arrangement: LayoutPanelTop,
  vocal_production: MicVocal,
};

export const SKILL_FOCUS_ICONS: Record<SkillFocusId, LucideIcon> = {
  "beat_making.drums": Drum,
  "beat_making.groove": Activity,
  "beat_making.bass": AudioWaveform,
  "beat_making.chords_melody": Piano,
  "beat_making.sampling": Scissors,
  "beat_making.sound_selection": Library,

  "mixing.balance": SlidersVertical,
  "mixing.eq": SlidersHorizontal,
  "mixing.dynamics": Gauge,
  "mixing.saturation": Flame,
  "mixing.space": Waves,
  "mixing.stereo": MoveHorizontal,
  "mixing.automation": Spline,
  "mixing.translation": Headphones,

  "mastering.tonal_balance": Contrast,
  "mastering.dynamics": Gauge,
  "mastering.loudness": Volume2,
  "mastering.stereo": Orbit,
  "mastering.references": ChartColumn,
  "mastering.delivery": Package,

  "sound_design.synthesis": Keyboard,
  "sound_design.advanced_synthesis": Sparkles,
  "sound_design.modulation": Repeat,
  "sound_design.sampling": Disc3,
  "sound_design.effects": Zap,
  "sound_design.layering": Layers,

  "recording.mic_technique": Mic,
  "recording.vocals": MicVocal,
  "recording.gain_staging": Cable,
  "recording.room": House,
  "recording.tracking": CircleDot,
  "recording.instruments": Guitar,

  "songwriting.melody": Music,
  "songwriting.harmony": Blend,
  "songwriting.lyrics": PenLine,
  "songwriting.song_form": LayoutList,
  "songwriting.hooks": Magnet,

  "arrangement.structure": LayoutPanelTop,
  "arrangement.transitions": Merge,
  "arrangement.energy": Rocket,
  "arrangement.variation": Shuffle,
  "arrangement.instrumentation": Boxes,

  "vocal_production.comping": Scissors,
  "vocal_production.tuning": Target,
  "vocal_production.chain": Workflow,
  "vocal_production.fx": WandSparkles,
  "vocal_production.layering": Copy,
};
