import { StyleSheet } from "react-native";

import { fontFamily } from "../../constants/fonts";
import { colors, radii, spacing, typography } from "../../constants/theme";

export const ACCENT_TINT = "rgba(255,61,0,0.10)";
const HAIRLINE = "rgba(255,255,255,0.08)";

export const challengeCreateStyles = StyleSheet.create({
  sheet: { flex: 1, backgroundColor: colors.background },
  centered: {
    flex: 1,
    alignItems: "center",
    justifyContent: "center",
    padding: spacing.lg,
    gap: spacing.md,
  },

  header: { paddingHorizontal: spacing.lg, paddingTop: spacing.lg, gap: spacing.lg },
  headerBar: { flexDirection: "row", alignItems: "center", justifyContent: "space-between" },
  iconButton: {
    width: 40,
    height: 40,
    borderRadius: radii.round,
    backgroundColor: colors.surface,
    borderWidth: 1,
    borderColor: HAIRLINE,
    alignItems: "center",
    justifyContent: "center",
  },
  iconButtonPlaceholder: { width: 40, height: 40 },
  progress: { flexDirection: "row", gap: 6 },
  progressSegment: { width: 28, height: 4, borderRadius: 2, backgroundColor: colors.border },
  progressSegmentDone: { backgroundColor: colors.primary },
  heading: {
    color: colors.textPrimary,
    fontFamily: fontFamily.heading,
    fontSize: 30,
    lineHeight: 34,
    letterSpacing: -0.8,
  },
  subheading: {
    color: colors.textSecondary,
    fontFamily: fontFamily.body,
    ...typography.body,
    marginTop: spacing.xs,
  },

  body: { flex: 1 },
  bodyContent: { paddingHorizontal: spacing.lg, paddingTop: spacing.lg, paddingBottom: spacing.xl },
  stepContent: { gap: spacing.md },

  footer: { paddingHorizontal: spacing.lg, paddingTop: spacing.sm, gap: spacing.sm },
  footerHint: {
    color: colors.textSecondary,
    fontFamily: fontFamily.body,
    ...typography.meta,
    textAlign: "center",
  },
  footerHintWarning: { color: colors.primary },

  search: {
    height: 44,
    borderRadius: radii.md,
    backgroundColor: colors.surface,
    borderWidth: 1,
    borderColor: HAIRLINE,
    paddingHorizontal: spacing.md,
    color: colors.textPrimary,
    fontFamily: fontFamily.body,
    ...typography.body,
  },
  grid: { flexDirection: "row", flexWrap: "wrap", rowGap: spacing.lg },
  tileCell: { width: "33.333%", paddingHorizontal: spacing.xs },
  tile: { alignItems: "center", gap: spacing.xs },
  tileDimmed: { opacity: 0.4 },
  tileName: {
    color: colors.textPrimary,
    fontFamily: fontFamily.bodyBold,
    ...typography.caption,
    textAlign: "center",
    maxWidth: "100%",
  },
  tileStatus: {
    color: colors.textSecondary,
    fontFamily: fontFamily.body,
    fontSize: 12,
    lineHeight: 16,
  },
  tileStatusLive: { color: colors.primary },
  checkBadge: {
    position: "absolute",
    right: 0,
    bottom: 0,
    width: 24,
    height: 24,
    borderRadius: 12,
    backgroundColor: colors.primary,
    borderWidth: 2,
    borderColor: colors.background,
    alignItems: "center",
    justifyContent: "center",
  },
  mutedText: {
    color: colors.textSecondary,
    fontFamily: fontFamily.body,
    ...typography.body,
    textAlign: "center",
  },

  presetList: { gap: 10 },
  presetCard: {
    flexDirection: "row",
    alignItems: "center",
    gap: spacing.md,
    padding: spacing.md,
    borderRadius: radii.lg,
    backgroundColor: colors.surface,
    borderWidth: 1,
    borderColor: HAIRLINE,
  },
  presetCardSelected: { borderColor: colors.primary, backgroundColor: ACCENT_TINT },
  presetCopy: { flex: 1, gap: 2 },
  presetTitle: {
    color: colors.textPrimary,
    fontFamily: fontFamily.heading,
    fontSize: 18,
    lineHeight: 24,
  },
  presetMeta: { color: colors.textSecondary, fontFamily: fontFamily.body, ...typography.meta },
  radio: {
    width: 22,
    height: 22,
    borderRadius: 11,
    borderWidth: 2,
    borderColor: colors.border,
    alignItems: "center",
    justifyContent: "center",
  },
  radioSelected: { borderColor: colors.primary },
  radioDot: { width: 10, height: 10, borderRadius: 5, backgroundColor: colors.primary },

  sectionLabel: {
    color: colors.textSecondary,
    fontFamily: fontFamily.bodyMedium,
    fontSize: 12,
    lineHeight: 16,
    letterSpacing: 1,
    textTransform: "uppercase",
    marginTop: spacing.md,
  },
  tuneCard: {
    borderRadius: radii.lg,
    backgroundColor: colors.surface,
    borderWidth: 1,
    borderColor: HAIRLINE,
    paddingHorizontal: spacing.md,
  },
  stepperRow: {
    flexDirection: "row",
    alignItems: "center",
    paddingVertical: spacing.md,
    gap: spacing.md,
  },
  stepperDivider: { height: 1, backgroundColor: HAIRLINE },
  stepperLabel: {
    flex: 1,
    color: colors.textPrimary,
    fontFamily: fontFamily.bodyMedium,
    ...typography.body,
  },
  stepperButton: {
    width: 40,
    height: 40,
    borderRadius: 20,
    backgroundColor: colors.background,
    borderWidth: 1,
    borderColor: HAIRLINE,
    alignItems: "center",
    justifyContent: "center",
  },
  stepperButtonDisabled: { opacity: 0.3 },
  stepperButtonPressed: { transform: [{ scale: 0.92 }] },
  stepperValue: {
    minWidth: 40,
    textAlign: "center",
    color: colors.textPrimary,
    fontFamily: fontFamily.heading,
    fontSize: 22,
    lineHeight: 28,
    fontVariant: ["tabular-nums"],
  },
  pace: {
    color: colors.textSecondary,
    fontFamily: fontFamily.body,
    ...typography.meta,
    textAlign: "center",
  },

  vsCard: {
    borderRadius: radii.xl,
    backgroundColor: colors.surface,
    borderWidth: 1,
    borderColor: HAIRLINE,
    paddingVertical: spacing.xl,
    paddingHorizontal: spacing.md,
    overflow: "hidden",
  },
  vsSlash: {
    position: "absolute",
    left: "-20%",
    right: "-20%",
    top: "50%",
    height: 2,
    backgroundColor: colors.primary,
    opacity: 0.55,
    transform: [{ rotate: "-12deg" }],
    shadowColor: colors.primary,
    shadowOpacity: 0.9,
    shadowRadius: 12,
    shadowOffset: { width: 0, height: 0 },
  },
  vsRow: { flexDirection: "row", alignItems: "center", justifyContent: "space-between" },
  vsSide: { flex: 1, alignItems: "center", gap: spacing.sm },
  vsName: {
    color: colors.textPrimary,
    fontFamily: fontFamily.heading,
    fontSize: 18,
    lineHeight: 22,
    letterSpacing: -0.3,
    maxWidth: "100%",
  },
  vsDisc: {
    width: 52,
    height: 52,
    borderRadius: 26,
    backgroundColor: colors.background,
    borderWidth: 2,
    borderColor: colors.primary,
    alignItems: "center",
    justifyContent: "center",
  },
  vsText: {
    color: colors.primary,
    fontFamily: fontFamily.heading,
    fontSize: 18,
    letterSpacing: -0.3,
  },

  chips: { flexDirection: "row", flexWrap: "wrap", gap: spacing.sm, justifyContent: "center" },
  chip: {
    flexDirection: "row",
    alignItems: "center",
    gap: 6,
    paddingVertical: 6,
    paddingHorizontal: spacing.sm + 2,
    borderRadius: radii.round,
    backgroundColor: colors.surface,
    borderWidth: 1,
    borderColor: HAIRLINE,
  },
  chipText: { color: colors.textPrimary, fontFamily: fontFamily.bodyMedium, ...typography.meta },

  titleCard: {
    borderRadius: radii.lg,
    backgroundColor: colors.surface,
    borderWidth: 1,
    borderColor: HAIRLINE,
    padding: spacing.md,
    gap: spacing.xs,
  },
  titleRow: { flexDirection: "row", alignItems: "center", gap: spacing.sm },
  titleText: {
    flex: 1,
    color: colors.textPrimary,
    fontFamily: fontFamily.bodyBold,
    ...typography.body,
  },
  titleInput: {
    flex: 1,
    color: colors.textPrimary,
    fontFamily: fontFamily.bodyBold,
    ...typography.body,
    paddingVertical: 0,
  },
  linkText: { color: colors.primary, fontFamily: fontFamily.bodyBold, ...typography.meta },

  errorBanner: {
    borderRadius: radii.md,
    borderWidth: 1,
    borderColor: "rgba(255,68,68,0.35)",
    backgroundColor: "rgba(255,68,68,0.08)",
    padding: spacing.md,
  },
  errorText: { color: colors.textPrimary, fontFamily: fontFamily.body, ...typography.meta },

  sentBadge: {
    width: 88,
    height: 88,
    borderRadius: 44,
    backgroundColor: colors.primary,
    alignItems: "center",
    justifyContent: "center",
    shadowColor: colors.primary,
    shadowOpacity: 0.6,
    shadowRadius: 24,
    shadowOffset: { width: 0, height: 0 },
  },
  sentCopy: { alignItems: "center", gap: 6 },
  sentActions: { alignSelf: "stretch", marginTop: spacing.sm },
  sentTitle: {
    color: colors.textPrimary,
    fontFamily: fontFamily.heading,
    fontSize: 28,
    lineHeight: 34,
    letterSpacing: -0.6,
    textAlign: "center",
  },
});
