import { StyleSheet } from "react-native";

import { fontFamily } from "../../constants/fonts";
import { colors, motion, radii, spacing, typography, ui } from "../../constants/theme";

export const sessionSetupStyles = StyleSheet.create({
  flex: { flex: 1 },
  header: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    paddingHorizontal: spacing.md,
    paddingBottom: spacing.sm,
  },
  closePlaceholder: { width: 40, height: 40 },
  title: {
    color: colors.textPrimary,
    fontFamily: fontFamily.heading,
    ...typography.screenTitle,
  },
  closeBtn: {
    width: 40,
    height: 40,
    borderRadius: 20,
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: colors.surface,
    borderWidth: 1,
    borderColor: colors.border,
  },
  closeText: { color: colors.textPrimary, fontSize: 18, fontFamily: fontFamily.bodyBold },
  scroll: { paddingHorizontal: ui.screenPadding, paddingBottom: spacing.xxl },
  sectionLabel: {
    marginTop: ui.stackGap,
    marginBottom: spacing.sm,
    color: colors.textSecondary,
    fontFamily: fontFamily.bodyBold,
    ...typography.meta,
  },
  sectionLabelFirst: {
    marginTop: 0,
  },
  typeColumn: { gap: spacing.sm },
  optionalToggle: {
    marginTop: ui.sectionGap,
    borderRadius: ui.cardRadius,
    borderWidth: 1,
    borderColor: colors.border,
    backgroundColor: colors.surface,
    paddingHorizontal: spacing.md,
    paddingVertical: spacing.sm,
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
  },
  optionalTogglePressed: {
    opacity: motion.pressOpacity,
    transform: [{ scale: motion.pressScale }],
  },
  optionalToggleText: {
    color: colors.textPrimary,
    fontFamily: fontFamily.bodyMedium,
    ...typography.meta,
  },
  optionalToggleChevron: {
    color: colors.textSecondary,
    fontFamily: fontFamily.bodyBold,
    ...typography.body,
  },
  optionalSection: {
    marginTop: spacing.sm,
    paddingBottom: spacing.sm,
  },
  typeCardPressable: {
    borderRadius: radii.lg,
  },
  typeCardPressed: {
    opacity: 0.92,
    transform: [{ scale: 0.985 }],
  },
  typeCardOuter: {
    borderRadius: ui.cardRadius,
    borderWidth: ui.cardBorderWidth,
    borderColor: colors.border,
    overflow: "hidden",
    backgroundColor: colors.surface,
  },
  typeGradientActive: {
    position: "relative",
    paddingVertical: spacing.lg,
    paddingHorizontal: spacing.md,
    minHeight: 88,
    overflow: "hidden",
    justifyContent: "center",
  },
  typePatternLayer: {
    ...StyleSheet.absoluteFillObject,
    opacity: 0.95,
  },
  typeRow: {
    flexDirection: "row",
    alignItems: "center",
    gap: spacing.md,
    zIndex: 1,
  },
  typeIconBadge: {
    width: 48,
    height: 48,
    borderRadius: 14,
    backgroundColor: "rgba(0,0,0,0.22)",
    alignItems: "center",
    justifyContent: "center",
    borderWidth: 1,
    borderColor: "rgba(255,255,255,0.28)",
  },
  typeIconBadgeMuted: {
    width: 48,
    height: 48,
    borderRadius: 14,
    backgroundColor: colors.background,
    alignItems: "center",
    justifyContent: "center",
    borderWidth: 1,
  },
  patternRoot: {
    ...StyleSheet.absoluteFillObject,
    justifyContent: "center",
  },
  patternBeatRow: {
    flexDirection: "row",
    alignItems: "flex-end",
    justifyContent: "space-between",
    height: 44,
    paddingHorizontal: spacing.sm,
    opacity: 0.35,
    gap: 4,
  },
  patternBeatBar: {
    flex: 1,
    maxWidth: 10,
    borderRadius: 3,
    backgroundColor: "rgba(255,255,255,0.9)",
  },
  patternMixRow: {
    flexDirection: "row",
    alignItems: "flex-end",
    justifyContent: "space-between",
    height: 40,
    paddingHorizontal: spacing.md,
    opacity: 0.32,
    gap: 5,
  },
  patternMixTrack: {
    flex: 1,
    alignItems: "center",
    justifyContent: "flex-end",
    height: 40,
  },
  patternMixCap: {
    width: 6,
    borderRadius: 3,
    backgroundColor: "rgba(255,255,255,0.88)",
  },
  patternSoundRow: {
    flexDirection: "row",
    gap: 10,
    marginBottom: 7,
    paddingHorizontal: spacing.sm,
    opacity: 0.28,
  },
  patternSoundRowOffset: {
    marginLeft: 14,
  },
  patternSoundDot: {
    width: 5,
    height: 5,
    borderRadius: 2.5,
    backgroundColor: "rgba(255,255,255,0.85)",
  },
  typeInner: {
    paddingVertical: spacing.lg,
    paddingHorizontal: spacing.md,
    flexDirection: "row",
    alignItems: "center",
    gap: spacing.md,
  },
  typeLabel: { color: "#fff", fontFamily: fontFamily.heading, ...typography.subheadline },
  typeLabelMuted: {
    color: colors.textPrimary,
    fontFamily: fontFamily.heading,
    ...typography.cardTitle,
    flex: 1,
  },
  notes: {
    minHeight: 100,
    borderRadius: ui.cardRadius,
    borderWidth: ui.cardBorderWidth,
    borderColor: colors.border,
    backgroundColor: colors.surface,
    color: colors.textPrimary,
    padding: spacing.md,
    fontFamily: fontFamily.body,
    ...typography.body,
  },
  counter: {
    alignSelf: "flex-end",
    color: colors.textSecondary,
    ...typography.meta,
    marginTop: 4,
  },
  moodRow: { flexDirection: "row", gap: spacing.sm, flexWrap: "wrap" },
  moodBtn: {
    width: 52,
    height: 52,
    borderRadius: 26,
    backgroundColor: colors.surface,
    borderWidth: 1,
    borderColor: colors.border,
    alignItems: "center",
    justifyContent: "center",
  },
  moodBtnActive: { borderColor: colors.primary, backgroundColor: "rgba(255,61,0,0.15)" },
  moodBtnPressed: { opacity: motion.pressOpacity, transform: [{ scale: motion.pressScaleStrong }] },
  tagWrap: { flexDirection: "row", flexWrap: "wrap", gap: spacing.xs },
  tagChip: {
    paddingHorizontal: spacing.sm,
    paddingVertical: 6,
    borderRadius: radii.round,
    backgroundColor: "rgba(162,89,255,0.2)",
    borderWidth: 1,
    borderColor: colors.secondary,
  },
  tagChipPressed: { opacity: motion.pressOpacity },
  tagText: { color: colors.textPrimary, fontFamily: fontFamily.bodyMedium, ...typography.meta },
  tagInputRow: {
    flexDirection: "row",
    alignItems: "center",
    gap: spacing.sm,
    marginTop: spacing.sm,
  },
  tagField: {
    flex: 1,
    borderRadius: ui.cardRadius,
    borderWidth: ui.cardBorderWidth,
    borderColor: colors.border,
    backgroundColor: colors.surface,
    color: colors.textPrimary,
    paddingHorizontal: spacing.md,
    paddingVertical: 12,
    fontFamily: fontFamily.body,
  },
  addTagBtn: {
    width: 44,
    height: 44,
    borderRadius: ui.cardRadius,
    backgroundColor: colors.surface,
    borderWidth: 1,
    borderColor: colors.border,
    alignItems: "center",
    justifyContent: "center",
  },
  addTagBtnPressed: { opacity: motion.pressOpacity, transform: [{ scale: motion.pressScale }] },
  addTagPlus: { color: colors.primary, fontSize: 22, fontFamily: fontFamily.bodyBold },
  suggestedRow: {
    flexDirection: "row",
    flexWrap: "wrap",
    gap: spacing.sm,
    marginTop: spacing.sm,
  },
  suggestedChip: {
    paddingHorizontal: spacing.md,
    paddingVertical: 8,
    borderRadius: radii.round,
    backgroundColor: colors.surface,
    borderWidth: 1,
    borderColor: colors.border,
  },
  suggestedChipPressed: { opacity: motion.pressOpacity },
  suggestedText: {
    color: colors.textSecondary,
    fontFamily: fontFamily.body,
    ...typography.meta,
  },
  tagError: {
    color: colors.danger,
    ...typography.caption,
    marginTop: spacing.xs,
  },
  error: { color: colors.danger, marginTop: spacing.md, ...typography.meta },
  footer: {
    padding: spacing.md,
    borderTopWidth: 1,
    borderTopColor: colors.border,
    backgroundColor: colors.background,
  },
});
