import { StyleSheet } from "react-native";

import { fontFamily } from "../../constants/fonts";
import { colors, motion, radii, spacing, typography, ui } from "../../constants/theme";

export const styles = StyleSheet.create({
  safe: { flex: 1, backgroundColor: colors.background, padding: ui.screenPadding },
  centered: {
    flex: 1,
    justifyContent: "center",
    alignItems: "center",
    gap: spacing.md,
    padding: spacing.lg,
  },
  scrollContent: { paddingBottom: spacing.xl },
  heroCard: {
    borderRadius: 24,
    padding: spacing.lg,
    paddingTop: spacing.xl,
    alignItems: "center",
    gap: spacing.sm,
    borderWidth: 1,
    borderColor: "rgba(255,61,0,0.22)",
    overflow: "hidden",
  },
  heroEyebrow: {
    color: colors.success,
    fontFamily: fontFamily.bodyBold,
    ...typography.caption,
    letterSpacing: 1.2,
    textTransform: "uppercase",
  },
  bigDur: {
    color: colors.textPrimary,
    fontFamily: fontFamily.heading,
    fontSize: 44,
    lineHeight: 48,
    letterSpacing: -1,
    textAlign: "center",
  },
  metaRow: {
    flexDirection: "row",
    flexWrap: "wrap",
    justifyContent: "center",
    gap: spacing.xs,
    marginTop: spacing.xs,
  },
  typePill: {
    borderRadius: 999,
    borderWidth: 1,
    borderColor: "rgba(255,61,0,0.45)",
    backgroundColor: "rgba(255,61,0,0.12)",
    paddingHorizontal: spacing.sm,
    paddingVertical: 6,
  },
  typePillText: {
    color: colors.textPrimary,
    fontFamily: fontFamily.bodyBold,
    ...typography.caption,
  },
  moodPill: {
    borderRadius: 999,
    borderWidth: 1,
    borderColor: "rgba(162,89,255,0.4)",
    backgroundColor: "rgba(162,89,255,0.12)",
    paddingHorizontal: spacing.sm,
    paddingVertical: 6,
  },
  moodPillText: {
    color: colors.textPrimary,
    fontFamily: fontFamily.bodyBold,
    ...typography.caption,
  },
  statGrid: {
    flexDirection: "row",
    flexWrap: "wrap",
    justifyContent: "center",
    gap: spacing.sm,
    width: "100%",
    marginTop: spacing.sm,
  },
  xpHintInline: {
    color: "#f59e0b",
    ...typography.caption,
    fontFamily: fontFamily.bodyMedium,
    textAlign: "center",
    paddingHorizontal: spacing.md,
  },
  levelLine: {
    color: colors.textSecondary,
    ...typography.caption,
    textAlign: "center",
    paddingHorizontal: spacing.md,
  },
  punchline: {
    color: colors.textPrimary,
    fontFamily: fontFamily.bodyBold,
    ...typography.body,
    textAlign: "center",
    marginTop: spacing.xs,
    paddingHorizontal: spacing.sm,
    lineHeight: 22,
  },
  loadingTitle: {
    color: colors.textPrimary,
    fontFamily: fontFamily.heading,
    ...typography.screenTitle,
    textAlign: "center",
  },
  muted: { color: colors.textSecondary, ...typography.meta, textAlign: "center" },
  actions: { marginTop: spacing.xl, gap: spacing.md },
  focusCard: {
    marginTop: spacing.lg,
    borderRadius: radii.xl,
    borderWidth: 1,
    borderColor: colors.border,
    backgroundColor: colors.surface,
    padding: spacing.lg,
  },
  focusEyebrow: {
    fontFamily: fontFamily.bodyBold,
    ...typography.caption,
    letterSpacing: 1.2,
    textTransform: "uppercase",
    marginBottom: spacing.xs,
  },
  focusCardHeader: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    gap: spacing.sm,
  },
  focusCardTitle: {
    flexShrink: 1,
    color: colors.textPrimary,
    fontFamily: fontFamily.heading,
    ...typography.cardTitle,
  },
  focusCardHint: {
    marginTop: spacing.xs,
    color: colors.textSecondary,
    ...typography.meta,
  },
  focusStatus: { flexDirection: "row", alignItems: "center", gap: spacing.xs, minHeight: 20 },
  focusStatusText: {
    color: colors.textSecondary,
    fontFamily: fontFamily.bodyMedium,
    ...typography.meta,
  },
  focusStatusSaved: { color: colors.success },
  focusErrorRow: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    gap: spacing.sm,
    marginTop: spacing.md,
    paddingLeft: spacing.md,
    borderRadius: radii.sm,
    backgroundColor: "rgba(255,68,68,0.1)",
  },
  focusErrorText: { flexShrink: 1, color: colors.danger, ...typography.meta },
  focusRetry: { minHeight: 44, justifyContent: "center", paddingHorizontal: spacing.md },
  focusRetryPressed: { opacity: motion.pressOpacity, transform: [{ scale: motion.pressScale }] },
  focusRetryText: {
    color: colors.textPrimary,
    fontFamily: fontFamily.bodyBold,
    ...typography.meta,
  },
  focusFootnote: { marginTop: spacing.md, color: colors.textSecondary, ...typography.meta },
  skillTreeLink: {
    marginTop: spacing.lg,
    paddingTop: spacing.md,
    borderTopWidth: 1,
    borderTopColor: colors.border,
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    minHeight: 44,
  },
  skillTreeLinkText: {
    color: colors.textPrimary,
    fontFamily: fontFamily.bodyBold,
    ...typography.caption,
  },
  branchSection: { marginTop: spacing.lg, gap: spacing.sm },
  branchHeader: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    gap: spacing.sm,
  },
  branchTitle: {
    flexShrink: 1,
    color: colors.textSecondary,
    fontFamily: fontFamily.bodyBold,
    ...typography.meta,
    letterSpacing: 0.6,
    textTransform: "uppercase",
  },
  fullPassPill: {
    flexDirection: "row",
    alignItems: "center",
    gap: 6,
    minHeight: 32,
    paddingHorizontal: spacing.sm + 4,
    borderRadius: radii.round,
    borderWidth: 1,
    borderColor: colors.border,
    marginLeft: "auto",
  },
  fullPassText: {
    color: colors.textSecondary,
    fontFamily: fontFamily.bodyBold,
    ...typography.meta,
  },
  fullPassTextActive: { color: colors.textPrimary },
  areaTimePreview: {
    color: colors.textPrimary,
    fontFamily: fontFamily.bodyMedium,
    ...typography.meta,
  },
  weightControl: {
    flexDirection: "row",
    gap: 6,
    padding: 4,
    borderRadius: radii.round,
    backgroundColor: "rgba(255,255,255,0.04)",
  },
  weightSegment: {
    flex: 1,
    minHeight: 36,
    alignItems: "center",
    justifyContent: "center",
    borderRadius: radii.round,
    borderWidth: 1,
    borderColor: "transparent",
  },
  weightSegmentText: {
    color: colors.textSecondary,
    fontFamily: fontFamily.bodyBold,
    ...typography.meta,
  },
  weightSegmentTextActive: { color: colors.textPrimary },
  tileRow: { flexDirection: "row", gap: spacing.sm },
  tileSpacer: { flex: 1 },
  tile: {
    flex: 1,
    minHeight: 124,
    padding: 14,
    gap: 6,
    borderRadius: radii.lg,
    borderCurve: "continuous",
    borderWidth: 1,
    borderColor: colors.border,
    backgroundColor: colors.background,
  },
  tilePressed: { transform: [{ scale: 0.97 }] },
  tileTopRow: { flexDirection: "row", alignItems: "center", justifyContent: "space-between" },
  tileIcon: {
    width: 32,
    height: 32,
    borderRadius: radii.round,
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: "rgba(255,255,255,0.06)",
  },
  starButton: {
    width: 32,
    height: 32,
    borderRadius: radii.round,
    alignItems: "center",
    justifyContent: "center",
  },
  tileLabel: {
    color: colors.textPrimary,
    fontFamily: fontFamily.bodyBold,
    ...typography.caption,
  },
  tileCovers: { color: colors.textSecondary, ...typography.meta },
  tileProgress: { marginTop: "auto", paddingTop: spacing.xs, gap: 6 },
  progressRow: { flexDirection: "row", alignItems: "baseline", justifyContent: "space-between" },
  progressGained: { fontFamily: fontFamily.bodyBold, ...typography.meta },
  progressLevel: {
    marginLeft: "auto",
    color: colors.textSecondary,
    fontFamily: fontFamily.bodyMedium,
    ...typography.meta,
  },
  progressTrack: {
    height: 4,
    borderRadius: radii.round,
    backgroundColor: "rgba(255,255,255,0.08)",
    overflow: "hidden",
  },
  progressFill: {
    position: "absolute",
    top: 0,
    bottom: 0,
    left: 0,
    right: 0,
    transformOrigin: "left",
  },
  progressCaption: { color: colors.textSecondary, fontSize: 12, lineHeight: 16 },
  progressCaptionLevelUp: { color: colors.success, fontFamily: fontFamily.bodyBold },
});
