import { StyleSheet } from "react-native";

import { fontFamily } from "../../constants/fonts";
import { colors, radii, spacing, typography } from "../../constants/theme";

export const sessionActiveStyles = StyleSheet.create({
  safe: { flex: 1, backgroundColor: colors.background },
  flex: { flex: 1 },
  bootWrap: {
    flex: 1,
    alignItems: "center",
    justifyContent: "center",
    gap: spacing.md,
    paddingHorizontal: spacing.lg,
  },
  bootBackBtn: {
    paddingVertical: spacing.xs,
    paddingHorizontal: spacing.sm,
  },
  bootBackTxt: {
    color: colors.textSecondary,
    ...typography.caption,
    fontFamily: fontFamily.bodyBold,
  },
  minimizeStrip: {
    alignItems: "center",
    paddingTop: spacing.xs,
    paddingBottom: spacing.sm,
    gap: 6,
  },
  grabber: {
    width: 44,
    height: 5,
    borderRadius: 3,
    backgroundColor: colors.border,
  },
  minimizeHint: {
    color: colors.textSecondary,
    ...typography.caption,
    fontSize: 12,
  },
  header: { paddingHorizontal: spacing.md, gap: spacing.xs },
  badge: {
    alignSelf: "flex-start",
    paddingHorizontal: spacing.md,
    paddingVertical: 6,
    borderRadius: radii.round,
    backgroundColor: "rgba(255,61,0,0.2)",
    borderWidth: 1,
    borderColor: colors.primary,
  },
  badgeText: { color: colors.textPrimary, fontFamily: fontFamily.bodyBold, ...typography.caption },
  warn: { color: colors.textSecondary, ...typography.caption },
  content: { padding: spacing.md, paddingBottom: spacing.xxl, gap: spacing.md },
  insightCard: {
    borderRadius: radii.md,
    borderWidth: 1,
    borderColor: colors.border,
    backgroundColor: "rgba(162,89,255,0.08)",
    padding: spacing.md,
  },
  insightText: {
    color: colors.textSecondary,
    fontFamily: fontFamily.bodyMedium,
    ...typography.caption,
    textAlign: "center",
  },
  timerWrap: { alignItems: "center", marginVertical: spacing.lg },
  timer: {
    fontSize: 64,
    fontFamily: fontFamily.heading,
    color: colors.textPrimary,
    fontVariant: ["tabular-nums"],
  },
  subTimer: { marginTop: spacing.xs, color: colors.textSecondary, ...typography.body },
  card: {
    borderRadius: radii.lg,
    borderWidth: 1,
    borderColor: colors.border,
    backgroundColor: colors.surface,
    padding: spacing.md,
    gap: spacing.sm,
  },
  row: { color: colors.textPrimary, fontFamily: fontFamily.body, ...typography.body },
  moodRow: { marginBottom: spacing.xs },
  editLabel: {
    color: colors.textSecondary,
    fontFamily: fontFamily.bodyBold,
    ...typography.caption,
    marginBottom: spacing.xs,
  },
  typeRow: { flexDirection: "row", flexWrap: "wrap", gap: spacing.sm, marginBottom: spacing.sm },
  typeChip: {
    paddingHorizontal: spacing.sm,
    paddingVertical: 8,
    borderRadius: radii.round,
    borderWidth: 1,
    borderColor: colors.border,
    backgroundColor: colors.background,
  },
  typeChipActive: {
    borderColor: colors.primary,
    backgroundColor: "rgba(255,61,0,0.15)",
  },
  typeChipTxt: {
    color: colors.textSecondary,
    ...typography.caption,
    fontFamily: fontFamily.bodyMedium,
  },
  typeChipTxtActive: { color: colors.textPrimary },
  notesInput: {
    minHeight: 88,
    borderRadius: radii.md,
    borderWidth: 1,
    borderColor: colors.border,
    backgroundColor: colors.background,
    color: colors.textPrimary,
    padding: spacing.md,
    fontFamily: fontFamily.body,
    ...typography.body,
  },
  notesFooter: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    marginTop: spacing.xs,
  },
  counter: { color: colors.textSecondary, ...typography.caption },
  saveNotes: { color: colors.primary, fontFamily: fontFamily.bodyBold, ...typography.caption },
  tags: { flexDirection: "row", flexWrap: "wrap", gap: 6 },
  tag: {
    paddingHorizontal: spacing.sm,
    paddingVertical: 4,
    borderRadius: radii.round,
    backgroundColor: "rgba(162,89,255,0.2)",
  },
  tagTxt: { color: colors.textPrimary, ...typography.caption },
  err: { color: colors.danger, ...typography.caption },
  actions: { marginTop: spacing.sm },
  pauseOutline: {
    borderRadius: radii.lg,
    borderWidth: 1,
    borderColor: colors.border,
    paddingVertical: spacing.md,
    alignItems: "center",
    backgroundColor: colors.surface,
  },
  pauseText: { color: colors.textPrimary, fontFamily: fontFamily.bodyBold, ...typography.body },
  stopBtn: {
    marginTop: spacing.md,
    borderRadius: radii.lg,
    backgroundColor: "rgba(255,59,48,0.2)",
    borderWidth: 1,
    borderColor: colors.danger,
    paddingVertical: spacing.md,
    alignItems: "center",
  },
  stopTxt: { color: colors.danger, fontFamily: fontFamily.bodyBold, ...typography.body },
});
