import { StyleSheet } from "react-native";
import { type CSSAnimationProperties, cubicBezier } from "react-native-reanimated";

import { fontFamily } from "../../constants/fonts";
import { colors, motion, radii, spacing, typography, ui } from "../../constants/theme";

/** Slow breathe on first-session Add — rare, so a loop is allowed. */
export const ADD_NUDGE_PULSE = {
  animationName: {
    "0%": { transform: [{ scale: 1 }] },
    "50%": { transform: [{ scale: 1.03 }] },
    "100%": { transform: [{ scale: 1 }] },
  },
  animationDuration: 1600,
  animationIterationCount: "infinite",
  animationTimingFunction: cubicBezier(0.77, 0, 0.175, 1),
} as const satisfies CSSAnimationProperties;

export const styles = StyleSheet.create({
  safe: { flex: 1, backgroundColor: colors.background, padding: ui.screenPadding },
  centered: {
    flex: 1,
    justifyContent: "center",
    alignItems: "center",
    gap: spacing.md,
    padding: spacing.lg,
  },
  scrollContent: { paddingBottom: spacing.xl },
  heroCard: {
    borderRadius: 24,
    padding: spacing.lg,
    paddingTop: spacing.xl,
    alignItems: "center",
    gap: spacing.sm,
    borderWidth: 1,
    borderColor: "rgba(255,61,0,0.22)",
    overflow: "hidden",
  },
  heroEyebrow: {
    color: colors.success,
    fontFamily: fontFamily.bodyBold,
    ...typography.caption,
    letterSpacing: 1.2,
    textTransform: "uppercase",
  },
  bigDur: {
    color: colors.textPrimary,
    fontFamily: fontFamily.heading,
    fontSize: 44,
    lineHeight: 48,
    letterSpacing: -1,
    textAlign: "center",
  },
  metaRow: {
    flexDirection: "row",
    flexWrap: "wrap",
    justifyContent: "center",
    gap: spacing.xs,
    marginTop: spacing.xs,
  },
  typePill: {
    borderRadius: 999,
    borderWidth: 1,
    borderColor: "rgba(255,61,0,0.45)",
    backgroundColor: "rgba(255,61,0,0.12)",
    paddingHorizontal: spacing.sm,
    paddingVertical: 6,
  },
  typePillText: {
    color: colors.textPrimary,
    fontFamily: fontFamily.bodyBold,
    ...typography.caption,
  },
  moodPill: {
    borderRadius: 999,
    borderWidth: 1,
    borderColor: "rgba(162,89,255,0.4)",
    backgroundColor: "rgba(162,89,255,0.12)",
    paddingHorizontal: spacing.sm,
    paddingVertical: 6,
  },
  moodPillText: {
    color: colors.textPrimary,
    fontFamily: fontFamily.bodyBold,
    ...typography.caption,
  },
  statGrid: {
    flexDirection: "row",
    flexWrap: "wrap",
    justifyContent: "center",
    gap: spacing.sm,
    width: "100%",
    marginTop: spacing.sm,
  },
  xpHintInline: {
    color: "#f59e0b",
    ...typography.caption,
    fontFamily: fontFamily.bodyMedium,
    textAlign: "center",
    paddingHorizontal: spacing.md,
  },
  levelLine: {
    color: colors.textSecondary,
    ...typography.caption,
    textAlign: "center",
    paddingHorizontal: spacing.md,
  },
  punchline: {
    color: colors.textPrimary,
    fontFamily: fontFamily.bodyBold,
    ...typography.body,
    textAlign: "center",
    marginTop: spacing.xs,
    paddingHorizontal: spacing.sm,
    lineHeight: 22,
  },
  loadingTitle: {
    color: colors.textPrimary,
    fontFamily: fontFamily.heading,
    ...typography.screenTitle,
    textAlign: "center",
  },
  muted: { color: colors.textSecondary, ...typography.meta, textAlign: "center" },
  actions: { marginTop: spacing.xl, gap: spacing.md },
  focusCard: {
    marginTop: spacing.lg,
    borderRadius: radii.xl,
    borderWidth: 1,
    borderColor: colors.border,
    backgroundColor: colors.surface,
    padding: spacing.lg,
  },
  focusCardNudge: {
    borderColor: colors.primary,
    backgroundColor: "rgba(255,61,0,0.1)",
    boxShadow: "0 0 28px rgba(255,61,0,0.28)",
  },
  focusEyebrow: {
    fontFamily: fontFamily.bodyBold,
    ...typography.caption,
    letterSpacing: 1.2,
    textTransform: "uppercase",
    marginBottom: spacing.xs,
  },
  focusCardHeader: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    gap: spacing.sm,
  },
  focusCardTitle: {
    flexShrink: 1,
    color: colors.textPrimary,
    fontFamily: fontFamily.heading,
    ...typography.cardTitle,
  },
  focusCardHint: {
    marginTop: spacing.xs,
    color: colors.textSecondary,
    ...typography.meta,
  },
  workedOnList: { marginTop: spacing.md, gap: spacing.xs },
  workedOnRow: {
    flexDirection: "row",
    alignItems: "center",
    gap: spacing.sm,
    minHeight: 52,
  },
  workedOnRowMain: {
    flex: 1,
    flexDirection: "row",
    alignItems: "center",
    gap: spacing.sm,
    minHeight: 52,
  },
  workedOnName: {
    flex: 1,
    color: colors.textPrimary,
    fontFamily: fontFamily.bodyBold,
    ...typography.body,
  },
  workedOnLevel: {
    color: colors.success,
    fontFamily: fontFamily.bodyBold,
    ...typography.meta,
  },
  workedOnMinutes: {
    color: colors.textPrimary,
    fontFamily: fontFamily.heading,
    ...typography.subheadline,
    letterSpacing: -0.4,
  },
  workedOnRemove: {
    width: 44,
    height: 44,
    alignItems: "center",
    justifyContent: "center",
    borderRadius: radii.round,
    borderCurve: "continuous",
  },
  workedOnAdd: {
    flexDirection: "row",
    alignItems: "center",
    gap: spacing.sm,
    minHeight: 44,
    paddingVertical: spacing.xs,
  },
  workedOnAddText: {
    color: colors.textPrimary,
    fontFamily: fontFamily.bodyBold,
    ...typography.caption,
  },
  workedOnAddNudge: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    gap: spacing.sm,
    minHeight: 48,
    paddingHorizontal: spacing.md,
    borderRadius: radii.md,
    borderCurve: "continuous",
    backgroundColor: colors.primary,
  },
  workedOnAddNudgeText: {
    color: colors.textPrimary,
    fontFamily: fontFamily.bodyBold,
    ...typography.body,
  },
  addSheet: { flex: 1 },
  /** The title, set apart from the list by a divider so it never reads as a row. */
  addSheetHeader: {
    paddingBottom: spacing.md,
    marginBottom: spacing.md,
    borderBottomWidth: StyleSheet.hairlineWidth,
    borderBottomColor: colors.border,
  },
  addSheetTitle: {
    color: colors.textPrimary,
    fontFamily: fontFamily.heading,
    ...typography.cardTitle,
  },
  addSheetList: { paddingBottom: spacing.md, gap: spacing.lg },
  addSheetFooter: { paddingTop: spacing.md },
  addGroup: { gap: spacing.xs },
  addGroupTitle: {
    color: colors.textSecondary,
    fontFamily: fontFamily.bodyBold,
    ...typography.meta,
    letterSpacing: 0.6,
    textTransform: "uppercase",
    marginBottom: spacing.xs,
  },
  addGroupCard: {
    borderRadius: radii.md,
    borderWidth: 1,
    borderColor: colors.border,
    backgroundColor: colors.surface,
    overflow: "hidden",
  },
  addRow: {
    minHeight: 48,
    flexDirection: "row",
    alignItems: "center",
    gap: spacing.sm,
    paddingHorizontal: spacing.md,
  },
  addRowDivider: {
    borderTopWidth: StyleSheet.hairlineWidth,
    borderTopColor: colors.border,
  },
  addRowPressed: { backgroundColor: "rgba(255,255,255,0.05)" },
  addRowText: {
    flex: 1,
    color: colors.textSecondary,
    fontFamily: fontFamily.bodyMedium,
    ...typography.body,
  },
  addRowTextSelected: {
    color: colors.textPrimary,
    fontFamily: fontFamily.bodyBold,
  },
  addCheck: {
    width: 22,
    height: 22,
    borderRadius: 11,
    borderWidth: 1.5,
    borderColor: "rgba(255,255,255,0.25)",
    alignItems: "center",
    justifyContent: "center",
  },
  addCheckSelected: {
    borderColor: colors.primary,
    backgroundColor: colors.primary,
  },
  focusStatus: { flexDirection: "row", alignItems: "center", gap: spacing.xs, minHeight: 20 },
  focusStatusText: {
    color: colors.textSecondary,
    fontFamily: fontFamily.bodyMedium,
    ...typography.meta,
  },
  focusStatusSaved: { color: colors.success },
  focusErrorRow: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    gap: spacing.sm,
    marginTop: spacing.md,
    paddingLeft: spacing.md,
    borderRadius: radii.sm,
    backgroundColor: "rgba(255,68,68,0.1)",
  },
  focusErrorText: { flexShrink: 1, color: colors.danger, ...typography.meta },
  focusRetry: { minHeight: 44, justifyContent: "center", paddingHorizontal: spacing.md },
  focusRetryPressed: { opacity: motion.pressOpacity, transform: [{ scale: motion.pressScale }] },
  focusRetryText: {
    color: colors.textPrimary,
    fontFamily: fontFamily.bodyBold,
    ...typography.meta,
  },
  focusFootnote: { marginTop: spacing.md, color: colors.textSecondary, ...typography.meta },
  creditRow: {
    flexDirection: "row",
    alignItems: "center",
    gap: spacing.sm,
    minHeight: 52,
    paddingVertical: spacing.xs,
  },
  creditIcon: {
    width: 28,
    height: 28,
    borderRadius: radii.round,
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: "rgba(255,255,255,0.06)",
  },
  creditIconCounted: { backgroundColor: "rgba(34,197,94,0.14)" },
  creditText: { flex: 1, gap: 2 },
  creditTitle: {
    color: colors.textPrimary,
    fontFamily: fontFamily.bodyBold,
    ...typography.caption,
  },
  creditDetail: { color: colors.textSecondary, ...typography.meta },
  branchSection: { marginTop: spacing.lg, gap: spacing.sm },
  branchHeader: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    gap: spacing.sm,
  },
  branchTitle: {
    flexShrink: 1,
    color: colors.textSecondary,
    fontFamily: fontFamily.bodyBold,
    ...typography.meta,
    letterSpacing: 0.6,
    textTransform: "uppercase",
  },
  fullPassPill: {
    flexDirection: "row",
    alignItems: "center",
    gap: 6,
    minHeight: 32,
    paddingHorizontal: spacing.sm + 4,
    borderRadius: radii.round,
    borderWidth: 1,
    borderColor: colors.border,
    marginLeft: "auto",
  },
  fullPassText: {
    color: colors.textSecondary,
    fontFamily: fontFamily.bodyBold,
    ...typography.meta,
  },
  fullPassTextActive: { color: colors.textPrimary },
  areaTimePreview: {
    color: colors.textPrimary,
    fontFamily: fontFamily.bodyMedium,
    ...typography.meta,
  },
  weightControl: {
    flexDirection: "row",
    gap: 6,
    padding: 4,
    borderRadius: radii.round,
    backgroundColor: "rgba(255,255,255,0.04)",
  },
  weightSegment: {
    flex: 1,
    minHeight: 36,
    alignItems: "center",
    justifyContent: "center",
    borderRadius: radii.round,
    borderWidth: 1,
    borderColor: "transparent",
  },
  weightSegmentText: {
    color: colors.textSecondary,
    fontFamily: fontFamily.bodyBold,
    ...typography.meta,
  },
  weightSegmentTextActive: { color: colors.textPrimary },
  tileRow: { flexDirection: "row", gap: spacing.sm },
  tileSpacer: { flex: 1 },
  tile: {
    flex: 1,
    minHeight: 124,
    padding: 14,
    gap: 6,
    borderRadius: radii.lg,
    borderCurve: "continuous",
    borderWidth: 1,
    borderColor: colors.border,
    backgroundColor: colors.background,
  },
  tilePressed: { transform: [{ scale: 0.97 }] },
  tileTopRow: { flexDirection: "row", alignItems: "center", justifyContent: "space-between" },
  tileIcon: {
    width: 32,
    height: 32,
    borderRadius: radii.round,
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: "rgba(255,255,255,0.06)",
  },
  starButton: {
    width: 32,
    height: 32,
    borderRadius: radii.round,
    alignItems: "center",
    justifyContent: "center",
  },
  tileLabel: {
    color: colors.textPrimary,
    fontFamily: fontFamily.bodyBold,
    ...typography.caption,
  },
  tileCovers: { color: colors.textSecondary, ...typography.meta },
  tileProgress: { marginTop: "auto", paddingTop: spacing.xs, gap: 6 },
  progressRow: { flexDirection: "row", alignItems: "baseline", justifyContent: "space-between" },
  progressGained: { fontFamily: fontFamily.bodyBold, ...typography.meta },
  progressLevel: {
    marginLeft: "auto",
    color: colors.textSecondary,
    fontFamily: fontFamily.bodyMedium,
    ...typography.meta,
  },
  progressTrack: {
    height: 4,
    borderRadius: radii.round,
    backgroundColor: "rgba(255,255,255,0.08)",
    overflow: "hidden",
  },
  progressFill: {
    position: "absolute",
    top: 0,
    bottom: 0,
    left: 0,
    right: 0,
    transformOrigin: "left",
  },
  progressCaption: { color: colors.textSecondary, fontSize: 12, lineHeight: 16 },
  progressCaptionLevelUp: { color: colors.success, fontFamily: fontFamily.bodyBold },
});
