"""
Generate the searchable emoji catalog used by the reaction picker.
Run from repo: python mobile/scripts/generate_emoji_catalog.py
Needs npm (downloads two MIT-licensed datasets into a temp dir) and writes
mobile/lib/emojiCatalog.generated.ts.

Sources: unicode-emoji-json (names, groups, order) and emojilib (search keywords).
"""
from __future__ import annotations

import json
import subprocess
import tarfile
import tempfile
from pathlib import Path

OUT = Path(__file__).resolve().parent.parent / "lib" / "emojiCatalog.generated.ts"
PACKAGES = {"unicode-emoji-json": "0.9.0", "emojilib": "4.0.3"}
# iOS 17 renders Emoji 15.0; newer emoji would show as empty boxes on older phones.
MAX_EMOJI_VERSION = (15, 0)
MAX_KEYWORDS = 6
GROUP_KEYS = {
    "Smileys & Emotion": "smileys",
    "People & Body": "people",
    "Animals & Nature": "animals",
    "Food & Drink": "food",
    "Travel & Places": "travel",
    "Activities": "activities",
    "Objects": "objects",
    "Symbols": "symbols",
    "Flags": "flags",
}


def fetch(tmp: Path) -> tuple[dict, list, dict]:
    for name, version in PACKAGES.items():
        subprocess.run(
            ["npm", "pack", f"{name}@{version}", "--silent"], cwd=tmp, check=True, capture_output=True
        )
        with tarfile.open(tmp / f"{name}-{version}.tgz") as archive:
            archive.extractall(tmp / name)
    unicode_dir = tmp / "unicode-emoji-json" / "package"
    by_emoji = json.loads((unicode_dir / "data-by-emoji.json").read_text(encoding="utf-8"))
    ordered = json.loads((unicode_dir / "data-ordered-emoji.json").read_text(encoding="utf-8"))
    keywords = json.loads(
        (tmp / "emojilib" / "package" / "dist" / "emoji-en-US.json").read_text(encoding="utf-8")
    )
    return by_emoji, ordered, keywords


def version_tuple(value: str) -> tuple[int, int]:
    major, _, minor = value.partition(".")
    return int(major), int(minor or 0)


def search_terms(name: str, words: list[str]) -> str:
    """'name|keyword keyword ...' so search can tell an exact name apart from a keyword."""
    clean_name = name.lower().strip()
    keywords: list[str] = []
    for raw in words[: MAX_KEYWORDS + 1]:
        term = raw.replace("_", " ").lower().strip()
        if term and term != clean_name and term not in keywords:
            keywords.append(term)
    return f"{clean_name}|{' '.join(keywords)}"


def main() -> None:
    with tempfile.TemporaryDirectory() as tmp_dir:
        by_emoji, ordered, keywords = fetch(Path(tmp_dir))
    groups: dict[str, list[list[str]]] = {key: [] for key in GROUP_KEYS.values()}
    for emoji in ordered:
        info = by_emoji.get(emoji)
        if not info or version_tuple(info["emoji_version"]) > MAX_EMOJI_VERSION:
            continue
        group = GROUP_KEYS.get(info["group"])
        if group is None:
            continue
        groups[group].append([emoji, search_terms(info["name"], keywords.get(emoji, []))])

    body = ",\n".join(
        f"  {{ key: {json.dumps(key)}, emojis: {json.dumps(entries, ensure_ascii=False)} }}"
        for key, entries in groups.items()
        if entries
    )
    OUT.write_text(
        "// Generated by scripts/generate_emoji_catalog.py. Edit the generator, not this file.\n"
        "// Data: unicode-emoji-json and emojilib (both MIT).\n"
        "/** Emoji grouped like the iOS keyboard; each entry is [emoji, \"name|keywords\"]. */\n"
        "export const EMOJI_CATALOG: { key: string; emojis: [string, string][] }[] = [\n"
        f"{body},\n];\n",
        encoding="utf-8",
    )
    total = sum(len(entries) for entries in groups.values())
    print(f"Wrote {total} emoji to {OUT}")


if __name__ == "__main__":
    main()
