import { StyleSheet } from "react-native";

import { fontFamily } from "../../constants/fonts";
import { colors, radii, spacing, typography } from "../../constants/theme";

export const LOCKED_NODE_FILL = "#111111";
export const LOCKED_NODE_BORDER = "#262626";
export const LOCKED_ICON_COLOR = "#3d3d3d";
export const LOCKED_EDGE_COLOR = "#2a2a2a";

const glassSurface = {
  backgroundColor: "rgba(20,20,20,0.92)",
  borderWidth: 1,
  borderColor: "rgba(255,255,255,0.08)",
} as const;

export const styles = StyleSheet.create({
  screen: { flex: 1, backgroundColor: colors.background },
  viewport: { flex: 1, overflow: "hidden" },
  canvas: { position: "absolute" },
  layerFill: { position: "absolute", left: 0, top: 0 },

  header: {
    position: "absolute",
    left: 0,
    right: 0,
    top: 0,
    paddingHorizontal: spacing.md,
    gap: spacing.sm,
  },
  headerRow: { flexDirection: "row", alignItems: "center", gap: spacing.sm },
  headerAccessories: {
    flexDirection: "row",
    alignItems: "flex-start",
    justifyContent: "space-between",
    gap: spacing.sm,
  },
  statusChips: { flex: 1, gap: spacing.xs + 2, alignItems: "flex-start" },
  newUnlockChip: { borderColor: `${colors.primary}55` },
  overviewMap: {
    ...glassSurface,
    padding: 6,
    borderRadius: radii.lg,
    borderCurve: "continuous",
    boxShadow: "0 8px 24px rgba(0,0,0,0.45)",
  },
  overviewFrame: {
    position: "absolute",
    left: 0,
    top: 0,
    borderWidth: 1.5,
    borderColor: "rgba(255,255,255,0.75)",
    borderRadius: 4,
  },
  headerCopy: { flex: 1 },
  headerTitle: { color: colors.textPrimary, fontFamily: fontFamily.heading, ...typography.cardTitle },
  headerSummary: { color: colors.textSecondary, ...typography.meta },
  iconButton: {
    ...glassSurface,
    width: 44,
    height: 44,
    borderRadius: radii.round,
    alignItems: "center",
    justifyContent: "center",
  },
  pressed: { opacity: 0.85, transform: [{ scale: 0.95 }] },
  neglectedChip: {
    ...glassSurface,
    alignSelf: "flex-start",
    flexDirection: "row",
    alignItems: "center",
    gap: spacing.xs,
    paddingHorizontal: spacing.sm + 4,
    paddingVertical: 6,
    borderRadius: radii.round,
  },
  neglectedChipText: { color: colors.textPrimary, fontFamily: fontFamily.bodyMedium, ...typography.meta },
  loadingPill: {
    ...glassSurface,
    alignSelf: "center",
    flexDirection: "row",
    alignItems: "center",
    gap: spacing.xs,
    paddingHorizontal: spacing.sm + 4,
    paddingVertical: 6,
    borderRadius: radii.round,
  },

  footer: { position: "absolute", left: spacing.md, right: spacing.md, bottom: 0 },
  gestureHint: { color: colors.textSecondary, textAlign: "center", ...typography.meta },
  card: {
    ...glassSurface,
    borderRadius: radii.xl,
    borderCurve: "continuous",
    padding: spacing.md,
    gap: spacing.sm,
    boxShadow: "0 12px 32px rgba(0,0,0,0.5)",
  },
  cardHeader: { flexDirection: "row", alignItems: "center", gap: spacing.sm + 4 },
  cardIcon: {
    width: 44,
    height: 44,
    borderRadius: radii.sm,
    borderCurve: "continuous",
    alignItems: "center",
    justifyContent: "center",
  },
  cardTitleWrap: { flex: 1 },
  cardEyebrow: {
    fontFamily: fontFamily.bodyBold,
    fontSize: 11,
    letterSpacing: 1,
    textTransform: "uppercase",
  },
  cardTitle: { color: colors.textPrimary, fontFamily: fontFamily.heading, ...typography.cardTitle },
  cardLevelRow: { flexDirection: "row", alignItems: "baseline", justifyContent: "space-between" },
  cardLevel: { color: colors.textPrimary, fontFamily: fontFamily.bodyBold, ...typography.body },
  cardMeta: { color: colors.textSecondary, ...typography.meta },
  cardBody: { color: colors.textSecondary, fontFamily: fontFamily.body, ...typography.caption },
  closeButton: {
    width: 32,
    height: 32,
    borderRadius: radii.round,
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: "rgba(255,255,255,0.06)",
  },
  centeredState: { flex: 1, justifyContent: "center", padding: spacing.lg },

  node: { position: "absolute", alignItems: "center" },
  nodeBody: { alignItems: "center" },
  dimmable: { transitionProperty: "opacity", transitionDuration: 220 },
  nodeRing: { position: "absolute" },
  nodeCircle: {
    alignItems: "center",
    justifyContent: "center",
    borderRadius: radii.round,
    borderWidth: 1.5,
  },
  nodePulse: { position: "absolute", borderRadius: radii.round, borderWidth: 2 },
  levelBadge: {
    position: "absolute",
    right: -4,
    bottom: -4,
    minWidth: 20,
    height: 20,
    paddingHorizontal: 5,
    borderRadius: radii.round,
    alignItems: "center",
    justifyContent: "center",
    borderWidth: 2,
    borderColor: colors.background,
  },
  levelBadgeText: { color: colors.background, fontFamily: fontFamily.bodyBold, fontSize: 11 },
  nodeLabelWrap: { position: "absolute", alignItems: "center", transformOrigin: "center" },
  nodeLabel: {
    textAlign: "center",
    fontFamily: fontFamily.bodyMedium,
    fontSize: 12,
    lineHeight: 15,
    paddingHorizontal: 7,
    paddingVertical: 2,
    borderRadius: 8,
    overflow: "hidden",
    backgroundColor: "rgba(10,10,10,0.72)",
  },
  branchLabel: { fontFamily: fontFamily.bodyBold, fontSize: 13 },
  centerCount: { color: colors.textPrimary, fontFamily: fontFamily.heading, fontSize: 24, lineHeight: 28 },
  centerTotal: { color: colors.textSecondary, fontSize: 11, lineHeight: 13 },
  centerLabel: {
    color: colors.textSecondary,
    fontFamily: fontFamily.bodyBold,
    fontSize: 10,
    letterSpacing: 1,
    textTransform: "uppercase",
  },

  listContent: { paddingHorizontal: spacing.md, gap: spacing.md },
  listBranch: {
    backgroundColor: colors.surface,
    borderWidth: 1,
    borderColor: colors.border,
    borderRadius: radii.lg,
    borderCurve: "continuous",
    padding: spacing.md,
    gap: spacing.sm,
  },
  listRow: { flexDirection: "row", alignItems: "center", gap: spacing.sm + 4, minHeight: 44 },
  listRowIcon: {
    width: 32,
    height: 32,
    borderRadius: 10,
    alignItems: "center",
    justifyContent: "center",
  },
  listRowName: { flex: 1, color: colors.textPrimary, fontFamily: fontFamily.bodyMedium, ...typography.caption },
  listRowNameLocked: { color: colors.textSecondary },
  listRowMeta: { color: colors.textSecondary, ...typography.meta },
  listBranchTitle: { flex: 1, color: colors.textPrimary, fontFamily: fontFamily.bodyBold, ...typography.body },

  sectionBody: { flexDirection: "row", alignItems: "center", gap: spacing.md },
  sectionBranches: { flex: 1, gap: spacing.sm + 2 },
  sectionBranchesLabel: {
    color: colors.textSecondary,
    fontFamily: fontFamily.bodyBold,
    fontSize: 11,
    lineHeight: 14,
    letterSpacing: 0.8,
    textTransform: "uppercase",
  },
  sectionBranchRow: { gap: 6 },
  sectionBranchTop: { flexDirection: "row", alignItems: "center", gap: spacing.xs + 2 },
  sectionBranchName: { flex: 1, color: colors.textPrimary, fontFamily: fontFamily.bodyMedium, ...typography.meta },
  sectionBranchLevel: { color: colors.textSecondary, fontFamily: fontFamily.bodyBold, ...typography.meta },
  sectionEmpty: { flex: 1, color: colors.textSecondary, ...typography.meta },
  sectionPlaceholderBar: { height: 10, borderRadius: radii.round, backgroundColor: colors.border },
  thinTrack: { height: 4, borderRadius: radii.round, backgroundColor: "rgba(255,255,255,0.06)", overflow: "hidden" },
  thinFill: { height: 4, borderRadius: radii.round },
  sectionError: { flexDirection: "row", alignItems: "center", justifyContent: "space-between", gap: spacing.sm },
  sectionRetry: { color: colors.primary, fontFamily: fontFamily.bodyBold, ...typography.caption },
});
