import { StyleSheet } from "react-native";

import { fontFamily } from "../../../constants/fonts";
import { colors, radii, spacing, typography } from "../../../constants/theme";

const HAIRLINE = "rgba(255,255,255,0.08)";
const ACCENT_TINT = "rgba(255,61,0,0.12)";
const PRESSED = "rgba(255,255,255,0.05)";

export const duelBoardStyles = StyleSheet.create({
  board: { gap: spacing.lg, marginBottom: spacing.xl },
  section: { gap: spacing.sm },
  sectionHeader: { flexDirection: "row", alignItems: "baseline", gap: spacing.sm },
  sectionTitle: {
    color: colors.textPrimary,
    fontFamily: fontFamily.heading,
    fontSize: 20,
    lineHeight: 24,
    letterSpacing: -0.4,
  },
  sectionCount: {
    color: colors.textSecondary,
    fontFamily: fontFamily.bodyMedium,
    ...typography.meta,
  },

  card: {
    borderRadius: radii.xl,
    backgroundColor: colors.surface,
    borderWidth: 1,
    borderColor: HAIRLINE,
    overflow: "hidden",
  },

  rivalsContent: { gap: spacing.md, paddingRight: spacing.md },
  rival: { width: 64, alignItems: "center", gap: 6 },
  rivalDimmed: { opacity: 0.4 },
  rivalName: {
    color: colors.textPrimary,
    fontFamily: fontFamily.bodyMedium,
    fontSize: 12,
    lineHeight: 16,
    maxWidth: 64,
  },
  record: {
    color: colors.textSecondary,
    fontFamily: fontFamily.bodyBold,
    fontSize: 11,
    lineHeight: 14,
    fontVariant: ["tabular-nums"],
  },
  recordWinning: { color: colors.primary },
  newDuelCircle: {
    width: 56,
    height: 56,
    borderRadius: 28,
    borderWidth: 1.5,
    borderStyle: "dashed",
    borderColor: colors.primary,
    backgroundColor: ACCENT_TINT,
    alignItems: "center",
    justifyContent: "center",
  },
  liveDot: {
    position: "absolute",
    right: 2,
    bottom: 2,
    width: 14,
    height: 14,
    borderRadius: 7,
    backgroundColor: colors.primary,
    borderWidth: 2,
    borderColor: colors.background,
  },

  arena: { padding: spacing.lg, gap: spacing.lg },
  arenaTop: { flexDirection: "row", alignItems: "center", gap: spacing.sm },
  arenaTitle: {
    flex: 1,
    color: colors.textSecondary,
    fontFamily: fontFamily.bodyMedium,
    ...typography.meta,
  },
  daysChip: {
    flexDirection: "row",
    alignItems: "center",
    gap: 4,
    paddingVertical: 4,
    paddingHorizontal: spacing.sm,
    borderRadius: radii.round,
    backgroundColor: ACCENT_TINT,
  },
  daysChipText: {
    color: colors.primary,
    fontFamily: fontFamily.bodyMedium,
    fontSize: 12,
    lineHeight: 16,
  },
  vsRow: { flexDirection: "row", alignItems: "center", justifyContent: "space-between" },
  vsSide: { flex: 1, alignItems: "center", gap: spacing.xs },
  vsName: {
    color: colors.textPrimary,
    fontFamily: fontFamily.heading,
    fontSize: 16,
    lineHeight: 20,
    letterSpacing: -0.2,
    maxWidth: "100%",
  },
  vsCenter: { alignItems: "center", gap: 6 },
  vsDisc: {
    width: 40,
    height: 40,
    borderRadius: 20,
    backgroundColor: colors.background,
    borderWidth: 2,
    borderColor: colors.primary,
    alignItems: "center",
    justifyContent: "center",
  },
  vsText: {
    color: colors.primary,
    fontFamily: fontFamily.heading,
    fontSize: 14,
    letterSpacing: -0.2,
  },
  standing: {
    color: colors.textPrimary,
    fontFamily: fontFamily.heading,
    fontSize: 24,
    lineHeight: 28,
    letterSpacing: -0.6,
    textAlign: "center",
  },
  standingAccent: { color: colors.primary },
  bars: { gap: spacing.sm },
  barRow: { flexDirection: "row", alignItems: "center", gap: spacing.sm },
  barLabel: {
    width: 64,
    color: colors.textSecondary,
    fontFamily: fontFamily.bodyMedium,
    ...typography.meta,
  },
  barTrack: {
    flex: 1,
    height: 8,
    borderRadius: 4,
    backgroundColor: colors.border,
    overflow: "hidden",
  },
  barFill: { height: "100%", borderRadius: 4, backgroundColor: colors.textSecondary },
  barFillAccent: { backgroundColor: colors.primary },
  barValue: {
    minWidth: 36,
    textAlign: "right",
    color: colors.textPrimary,
    fontFamily: fontFamily.bodyBold,
    ...typography.meta,
  },
  arenaAction: { paddingHorizontal: spacing.lg, paddingBottom: spacing.lg },

  row: {
    flexDirection: "row",
    alignItems: "center",
    gap: spacing.md,
    minHeight: 68,
    paddingHorizontal: spacing.md,
    paddingVertical: spacing.sm,
  },
  rowPressed: { backgroundColor: PRESSED },
  rowDivider: {
    position: "absolute",
    top: 0,
    left: 72,
    right: 0,
    height: StyleSheet.hairlineWidth,
    backgroundColor: "rgba(255,255,255,0.12)",
  },
  rowCopy: { flex: 1, minWidth: 0, gap: 2 },
  rowTitle: {
    color: colors.textPrimary,
    fontFamily: fontFamily.bodyMedium,
    fontSize: 16,
    lineHeight: 21,
  },
  rowMeta: { color: colors.textSecondary, fontFamily: fontFamily.body, ...typography.meta },

  pill: {
    paddingVertical: 4,
    paddingHorizontal: spacing.sm + 2,
    borderRadius: radii.round,
    backgroundColor: colors.border,
  },
  pillAccent: { backgroundColor: ACCENT_TINT },
  pillText: {
    color: colors.textSecondary,
    fontFamily: fontFamily.bodyBold,
    fontSize: 12,
    lineHeight: 16,
  },
  pillTextAccent: { color: colors.primary },
  rematchPill: {
    minHeight: 36,
    justifyContent: "center",
    paddingHorizontal: spacing.md,
    borderRadius: radii.round,
    backgroundColor: colors.primary,
  },
  rematchPillText: {
    color: colors.textPrimary,
    fontFamily: fontFamily.bodyBold,
    fontSize: 13,
    lineHeight: 18,
  },

  textAction: { minHeight: 44, justifyContent: "center", paddingHorizontal: spacing.xs },
  textActionLabel: {
    color: colors.primary,
    fontFamily: fontFamily.bodyMedium,
    fontSize: 15,
    lineHeight: 20,
  },
  textActionMuted: { color: colors.textSecondary },
  textActionPressed: { opacity: 0.6 },

  empty: { padding: spacing.lg, gap: spacing.md, alignItems: "center" },
  emptyAvatars: { flexDirection: "row", marginBottom: spacing.xs },
  emptyAvatarOverlap: { marginLeft: -14 },
  emptyAvatarRing: { borderRadius: 30, borderWidth: 3, borderColor: colors.surface },
  emptyTitle: {
    color: colors.textPrimary,
    fontFamily: fontFamily.heading,
    fontSize: 26,
    lineHeight: 30,
    letterSpacing: -0.7,
    textAlign: "center",
  },
  emptyBody: {
    color: colors.textSecondary,
    fontFamily: fontFamily.body,
    ...typography.body,
    textAlign: "center",
    marginBottom: spacing.xs,
  },
  emptyAction: { alignSelf: "stretch" },

  skeletonBlock: { borderRadius: radii.xl, backgroundColor: colors.surface },
  skeletonArena: { height: 340 },
  skeletonList: { height: 136 },
  skeletonRivals: { flexDirection: "row", gap: spacing.md },
  skeletonCircle: { width: 56, height: 56, borderRadius: 28, backgroundColor: colors.surface },
});
