import { StyleSheet } from "react-native";

import { fontFamily } from "../../constants/fonts";
import { colors, radii, spacing, typography } from "../../constants/theme";

/** Icon column width, so row separators start where the text does. */
export const NOTIFICATION_ICON_SIZE = 40;

export const notificationStyles = StyleSheet.create({
  safe: { flex: 1, backgroundColor: colors.background },
  topRow: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    paddingHorizontal: spacing.md,
    minHeight: 44,
  },
  settingsButton: {
    width: 44,
    height: 44,
    marginRight: -spacing.sm,
    alignItems: "center",
    justifyContent: "center",
  },
  pressed: { opacity: 0.6 },
  screenTitle: {
    color: colors.textPrimary,
    fontFamily: fontFamily.heading,
    ...typography.screenTitle,
    paddingHorizontal: spacing.md,
    marginTop: spacing.xs,
  },
  // Text tabs with an accent underline, instead of a wall of pills.
  tabs: {
    flexGrow: 0,
    marginTop: spacing.md,
    borderBottomWidth: StyleSheet.hairlineWidth,
    borderBottomColor: colors.border,
  },
  tabsContent: { paddingHorizontal: spacing.md, gap: spacing.lg },
  tab: { paddingTop: spacing.xs, alignItems: "center" },
  tabText: {
    color: colors.textSecondary,
    fontFamily: fontFamily.bodyMedium,
    ...typography.caption,
    paddingBottom: spacing.sm,
  },
  tabTextOn: { color: colors.textPrimary, fontFamily: fontFamily.bodyBold },
  tabUnderline: {
    height: 2,
    alignSelf: "stretch",
    borderRadius: 1,
    backgroundColor: "transparent",
  },
  tabUnderlineOn: { backgroundColor: colors.primary },
  serverErrorBanner: {
    marginHorizontal: spacing.md,
    marginTop: spacing.sm,
    padding: spacing.sm,
    borderRadius: radii.md,
    borderWidth: 1,
    borderColor: "rgba(251,191,36,0.45)",
    backgroundColor: "rgba(251,191,36,0.1)",
    gap: spacing.xs,
  },
  serverErrorText: {
    color: colors.textPrimary,
    ...typography.caption,
    fontFamily: fontFamily.body,
  },
  serverErrorRetry: { alignSelf: "flex-start" },
  serverErrorRetryText: {
    color: colors.primary,
    fontFamily: fontFamily.bodyBold,
    ...typography.caption,
  },
  listFlex: { flex: 1 },
  loadingWrap: { flex: 1, paddingHorizontal: spacing.md },
  list: { paddingBottom: spacing.xxl, flexGrow: 1 },
  sectionHeader: {
    color: colors.textSecondary,
    fontFamily: fontFamily.bodyBold,
    ...typography.meta,
    letterSpacing: 0.6,
    textTransform: "uppercase",
    paddingHorizontal: spacing.md,
    paddingTop: spacing.lg,
    paddingBottom: spacing.xs,
    backgroundColor: colors.background,
  },
  separator: {
    height: StyleSheet.hairlineWidth,
    backgroundColor: colors.border,
    marginLeft: spacing.md + NOTIFICATION_ICON_SIZE + spacing.sm,
  },
  row: {
    flexDirection: "row",
    alignItems: "flex-start",
    gap: spacing.sm,
    paddingHorizontal: spacing.md,
    paddingVertical: spacing.sm + 2,
    backgroundColor: colors.background,
  },
  rowPressed: { backgroundColor: "rgba(255,255,255,0.04)" },
  icon: {
    width: NOTIFICATION_ICON_SIZE,
    height: NOTIFICATION_ICON_SIZE,
    borderRadius: NOTIFICATION_ICON_SIZE / 2,
    alignItems: "center",
    justifyContent: "center",
  },
  rowCopy: { flex: 1, minWidth: 0, gap: 2 },
  rowTitle: { color: colors.textPrimary, fontFamily: fontFamily.bodyBold, ...typography.body },
  rowBody: { color: colors.textSecondary, fontFamily: fontFamily.body, ...typography.caption },
  rowMeta: { alignItems: "flex-end", gap: spacing.xs, paddingTop: 2 },
  time: { color: colors.textSecondary, fontFamily: fontFamily.body, ...typography.meta },
  unreadDot: { width: 8, height: 8, borderRadius: 4, backgroundColor: colors.primary },
  deleteBtn: {
    backgroundColor: colors.danger,
    justifyContent: "center",
    paddingHorizontal: spacing.lg,
  },
  deleteTxt: { color: "#fff", fontFamily: fontFamily.bodyBold },
  // Preferences sheet
  prefsTitle: {
    color: colors.textPrimary,
    fontFamily: fontFamily.heading,
    ...typography.cardTitle,
    paddingBottom: spacing.md,
  },
  prefsScroll: { flex: 1 },
  prefsContent: { gap: spacing.lg, paddingBottom: spacing.lg },
  prefsGroupLabel: {
    color: colors.textSecondary,
    fontFamily: fontFamily.bodyBold,
    ...typography.meta,
    letterSpacing: 0.6,
    textTransform: "uppercase",
    marginBottom: spacing.xs,
  },
  prefsCard: {
    borderRadius: radii.md,
    borderWidth: 1,
    borderColor: colors.border,
    backgroundColor: colors.surface,
    overflow: "hidden",
  },
  prefsRow: {
    flexDirection: "row",
    alignItems: "center",
    gap: spacing.sm,
    minHeight: 52,
    paddingHorizontal: spacing.md,
    paddingVertical: spacing.sm,
  },
  prefsRowDivider: {
    borderTopWidth: StyleSheet.hairlineWidth,
    borderTopColor: colors.border,
  },
  prefsRowCopy: { flex: 1, gap: 2 },
  prefsRowLabel: {
    color: colors.textPrimary,
    fontFamily: fontFamily.bodyMedium,
    ...typography.body,
  },
  prefsRowHint: { color: colors.textSecondary, ...typography.meta },
  segment: {
    flexDirection: "row",
    padding: 3,
    borderRadius: radii.md,
    borderWidth: 1,
    borderColor: colors.border,
    backgroundColor: colors.surface,
  },
  segmentOption: {
    flex: 1,
    minHeight: 38,
    alignItems: "center",
    justifyContent: "center",
    borderRadius: radii.md - 3,
  },
  segmentOptionOn: { backgroundColor: "rgba(255,61,0,0.16)" },
  segmentText: {
    color: colors.textSecondary,
    fontFamily: fontFamily.bodyMedium,
    ...typography.caption,
  },
  segmentTextOn: { color: colors.textPrimary, fontFamily: fontFamily.bodyBold },
});
