import { StyleSheet } from "react-native";

import { fontFamily } from "../../constants/fonts";
import { colors, radii, spacing, typography } from "../../constants/theme";

export const styles = StyleSheet.create({
  wrap: { width: "100%", gap: spacing.sm },
  setupTitle: { color: colors.textPrimary, fontFamily: fontFamily.heading, ...typography.body },
  setupHint: { color: colors.textSecondary, fontFamily: fontFamily.body, ...typography.meta },
  headerRow: {
    flexDirection: "row",
    alignItems: "flex-start",
    justifyContent: "space-between",
    gap: spacing.sm,
  },
  headerRight: { alignItems: "flex-end", gap: spacing.xs },
  title: {
    color: colors.textSecondary,
    fontFamily: fontFamily.bodyBold,
    ...typography.caption,
    textTransform: "uppercase",
    letterSpacing: 0.8,
    flex: 1,
  },
  statusChip: {
    borderRadius: radii.round,
    borderWidth: 1,
    paddingHorizontal: spacing.sm,
    paddingVertical: 4,
  },
  statusChipText: {
    color: colors.textPrimary,
    fontFamily: fontFamily.bodyBold,
    fontSize: 11,
    letterSpacing: 0.3,
  },
  chip_goalComplete: {
    borderColor: "rgba(0,255,136,0.45)",
    backgroundColor: "rgba(0,255,136,0.12)",
  },
  chip_ahead: { borderColor: "rgba(0,255,136,0.35)", backgroundColor: "rgba(0,255,136,0.08)" },
  chip_onTrack: { borderColor: "rgba(162,89,255,0.4)", backgroundColor: "rgba(162,89,255,0.12)" },
  chip_atRisk: { borderColor: "rgba(245,158,11,0.45)", backgroundColor: "rgba(245,158,11,0.12)" },
  chip_offTrack: { borderColor: "rgba(255,68,68,0.4)", backgroundColor: "rgba(255,68,68,0.1)" },
  progressNumbers: {
    color: colors.textPrimary,
    fontFamily: fontFamily.heading,
    fontSize: 28,
    lineHeight: 34,
    letterSpacing: -0.5,
  },
  goalProgressTrack: {
    width: "100%",
    height: 10,
    borderRadius: radii.round,
    backgroundColor: "rgba(0,0,0,0.35)",
    borderWidth: 1,
    borderColor: colors.border,
    overflow: "hidden",
    position: "relative",
  },
  goalProgressFill: { height: "100%", backgroundColor: colors.primary },
  goalProgressMarker: {
    position: "absolute",
    top: -2,
    bottom: -2,
    width: 2,
    backgroundColor: "#ffffff",
    opacity: 0.85,
  },
  chipRow: { flexDirection: "row", gap: spacing.sm },
  chip: {
    minWidth: 52,
    minHeight: 44,
    borderRadius: radii.md,
    borderWidth: 1,
    borderColor: colors.border,
    backgroundColor: "rgba(255,255,255,0.04)",
    alignItems: "center",
    justifyContent: "center",
    paddingHorizontal: spacing.md,
  },
  chipActive: { borderColor: colors.primary, backgroundColor: "rgba(255,61,0,0.14)" },
  chipPressed: { opacity: 0.88 },
  chipDisabled: { opacity: 0.6 },
  chipText: { color: colors.textPrimary, fontFamily: fontFamily.bodyBold, ...typography.body },
  chipTextActive: { color: colors.primary },
  editBtn: { paddingVertical: 2, paddingHorizontal: spacing.xs },
  editBtnText: { color: colors.secondary, fontFamily: fontFamily.bodyBold, ...typography.meta },
});
